name: CI

on:
  pull_request:
    branches:
      - latest
  push:
    branches:
      - latest
    tags:
      - '*'

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18'
        check-latest: true
    - run: corepack enable pnpm
    - run: pnpm install
    - run: pnpm test
    - run: pnpm build
